/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113484-g9949c1dd78-20240131"
#endif /* AVUTIL_FFVERSION_H */
